basePath: /claiming/ext-vnd
consumes:
  - application/json
definitions:
  AccidentType:
    properties:
      accidentDate:
        format: date
        type: string
      accidentInd:
        maxLength: 1
        minLength: 1
        type: string
    type: object
  AddressType:
    properties:
      addressLineOne:
        maxLength: 40
        minLength: 1
        type: string
      addressLineTwo:
        maxLength: 40
        minLength: 1
        type: string
      locality:
        maxLength: 40
        minLength: 1
        type: string
      postcode:
        maxLength: 4
        minLength: 4
        type: string
    type: object
  BaseEclipseMedicalEventType:
    discriminator: baseEclipseMedicalEventType
    properties:
      admissionDate:
        format: date
        type: string
      dischargeDate:
        format: date
        type: string
      financialInterestDisclosureInd:
        maxLength: 1
        minLength: 1
        type: string
      id:
        maxLength: 2
        minLength: 2
        type: string
      ifcIssueCode:
        maxLength: 1
        minLength: 1
        type: string
      referral:
        $ref: '#/definitions/ReferralType'
      referralOverrideCode:
        maxLength: 1
        minLength: 1
        type: string
      serviceProvider:
        $ref: '#/definitions/ProviderType'
    required:
      - id
    type: object
  CoPaymentType:
    allOf:
      - $ref: '#/definitions/PatientPaymentType'
      - properties:
          daysRemaining:
            type: integer
        type: object
  ContactType:
    properties:
      emailAddress:
        maxLength: 128
        minLength: 5
        type: string
      name:
        type: string
      phoneNumber:
        maxLength: 19
        minLength: 8
        type: string
    type: object
  EclipseClaimSummaryType:
    discriminator: eclipseClaimSummaryType
    properties:
      accountReferenceId:
        type: string
    type: object
  ExcessPaymentType:
    allOf:
      - $ref: '#/definitions/PatientPaymentType'
      - properties:
          bonusAmount:
            type: integer
        type: object
  ExplanationType:
    properties:
      code:
        type: string
      text:
        type: string
    type: object
  FundMembershipStatusType:
    properties:
      currentMember:
        $ref: '#/definitions/IdentityType'
      currentMembership:
        $ref: '#/definitions/FundMembershipType'
      processDate:
        format: date
        type: string
      status:
        $ref: '#/definitions/StatusType'
    type: object
  FundMembershipType:
    properties:
      memberNumber:
        maxLength: 19
        minLength: 1
        type: string
      memberRefNumber:
        maxLength: 2
        minLength: 1
        type: string
      organisation:
        maxLength: 3
        minLength: 3
        type: string
    type: object
  FundPatientType:
    allOf:
      - $ref: '#/definitions/PatientType'
      - properties:
          alsoKnownAs:
            $ref: '#/definitions/IdentityType'
          healthFund:
            $ref: '#/definitions/FundMembershipType'
          medicare:
            $ref: '#/definitions/MembershipType'
        type: object
  HealthFundClaimEstimationType:
    properties:
      benefitLimitations:
        type: string
      exclusionDescription:
        type: string
      explanation:
        items:
          $ref: '#/definitions/ExplanationType'
        minItems: 1
        type: array
      financialStatus:
        type: string
      fundAssessmentCode:
        type: string
      fundReferenceId:
        type: string
      healthFundTable:
        $ref: '#/definitions/HealthFundTableType'
      medicalEvent:
        items:
          $ref: '#/definitions/HealthFundMedicalEventEstimationType'
        minItems: 1
        type: array
      patientCoPayment:
        $ref: '#/definitions/CoPaymentType'
      patientExcessPayment:
        $ref: '#/definitions/ExcessPaymentType'
      peaPotentialInd:
        type: string
    type: object
  HealthFundMedicalEventEstimationType:
    properties:
      id:
        type: string
      service:
        items:
          $ref: '#/definitions/HealthFundServiceEstimationType'
        minItems: 1
        type: array
    type: object
  HealthFundServiceEstimationType:
    properties:
      benefit:
        type: integer
      chargeAmount:
        type: string
      dateOfService:
        format: date
        type: string
      explanation:
        items:
          $ref: '#/definitions/ExplanationType'
        minItems: 1
        type: array
      fundAssessmentCode:
        type: string
      id:
        type: string
      itemNumber:
        type: string
      serviceCode:
        type: string
      serviceCodeTypeCode:
        type: string
    type: object
  HealthFundTableType:
    properties:
      tableDescription:
        type: string
      tableName:
        type: string
      tableScale:
        type: string
    type: object
  IdentityType:
    discriminator: identityType
    properties:
      dateOfBirth:
        format: date
        type: string
      familyName:
        type: string
      givenName:
        type: string
      secondInitial:
        maxLength: 1
        minLength: 1
        type: string
      sex:
        maxLength: 1
        minLength: 1
        type: string
    type: object
  MedicareClaimEstimationType:
    properties:
      fundLocationId:
        type: string
      lodgementDate:
        format: date
        type: string
      medicalEvent:
        items:
          $ref: '#/definitions/MedicareMedicalEventEstimationType'
        minItems: 1
        type: array
    type: object
  MedicareMedicalEventEstimationType:
    properties:
      id:
        type: string
      service:
        items:
          $ref: '#/definitions/MedicareServiceEstimationType'
        minItems: 1
        type: array
    type: object
  MedicareServiceEstimationType:
    properties:
      benefit:
        type: integer
      chargeAmount:
        type: string
      dateOfService:
        format: date
        type: string
      explanationCode:
        type: string
      id:
        type: string
      itemNumber:
        type: string
      scheduleFee:
        type: integer
    type: object
  MembershipStatusType:
    properties:
      currentMember:
        $ref: '#/definitions/IdentityType'
      currentMembership:
        $ref: '#/definitions/MembershipType'
      processDate:
        format: date
        type: string
      status:
        $ref: '#/definitions/StatusType'
    type: object
  MembershipType:
    properties:
      memberNumber:
        maxLength: 10
        minLength: 10
        type: string
      memberRefNumber:
        maxLength: 1
        minLength: 1
        type: string
    type: object
  OnlineEligibilityCheckClaimType:
    properties:
      accident:
        $ref: '#/definitions/AccidentType'
      accountReferenceId:
        type: string
      claimTypeCode:
        maxLength: 2
        minLength: 2
        type: string
      compensationClaimInd:
        maxLength: 1
        minLength: 1
        type: string
      emergencyAdmissionInd:
        maxLength: 1
        minLength: 1
        type: string
      facilityId:
        maxLength: 8
        minLength: 8
        type: string
      fundPayeeId:
        maxLength: 12
        minLength: 1
        type: string
      hospitalInd:
        maxLength: 1
        minLength: 1
        type: string
      lengthOfStay:
        type: integer
      medicalEvent:
        items:
          $ref: '#/definitions/OnlineEligibilityCheckMedicalEventType'
        minItems: 1
        type: array
      patient:
        $ref: '#/definitions/FundPatientType'
      peaRequestInd:
        maxLength: 1
        minLength: 1
        type: string
      presentingIllnessCode:
        type: string
      presentingIllnessItemNumber:
        type: string
      principalProvider:
        $ref: '#/definitions/ProviderType'
      sameDayInd:
        maxLength: 1
        minLength: 1
        type: string
      senderContact:
        $ref: '#/definitions/ContactType'
      serviceTypeCode:
        maxLength: 1
        minLength: 1
        type: string
      submissionAuthorityInd:
        maxLength: 1
        minLength: 1
        type: string
      typeCode:
        type: string
    required:
      - accountReferenceId
      - medicalEvent
      - patient
      - submissionAuthorityInd
      - typeCode
    type: object
  OnlineEligibilityCheckMedicalEventType:
    allOf:
      - $ref: '#/definitions/BaseEclipseMedicalEventType'
      - properties:
          service:
            items:
              $ref: '#/definitions/OnlineEligibilityCheckServiceType'
            minItems: 1
            type: array
        type: object
  OnlineEligibilityCheckRequestType:
    properties:
      claim:
        $ref: '#/definitions/OnlineEligibilityCheckClaimType'
      medicareEstimation:
        $ref: '#/definitions/MedicareClaimEstimationType'
    required:
      - claim
    type: object
  OnlineEligibilityCheckResponseType:
    properties:
      claimSummary:
        $ref: '#/definitions/EclipseClaimSummaryType'
      healthFundClaimEstimation:
        $ref: '#/definitions/HealthFundClaimEstimationType'
      healthFundStatus:
        $ref: '#/definitions/FundMembershipStatusType'
      medicareClaimEstimation:
        $ref: '#/definitions/MedicareClaimEstimationType'
      medicareStatus:
        $ref: '#/definitions/MembershipStatusType'
      status:
        type: string
    required:
      - status
    type: object
  OnlineEligibilityCheckServiceType:
    allOf:
      - $ref: '#/definitions/ServiceType'
      - properties:
          dateOfService:
            format: date
            type: string
          restrictionOverrideInd:
            maxLength: 1
            minLength: 1
            type: string
          serviceCode:
            type: string
          serviceCodeTypeCode:
            type: string
          serviceQuantity:
            type: integer
          serviceRate:
            type: integer
          timeDependantOverrideInd:
            maxLength: 1
            minLength: 1
            type: string
        type: object
  PatientPaymentType:
    discriminator: patientPaymentType
    properties:
      amount:
        type: integer
      amountDescription:
        type: string
    type: object
  PatientType:
    discriminator: patientType
    properties:
      identity:
        $ref: '#/definitions/IdentityType'
      residentialAddress:
        $ref: '#/definitions/AddressType'
    required:
      - identity
    type: object
  ProviderType:
    properties:
      providerNumber:
        maxLength: 8
        minLength: 8
        type: string
    required:
      - providerNumber
    type: object
  ReferralType:
    properties:
      issueDate:
        format: date
        type: string
      period:
        maxLength: 2
        minLength: 1
        type: string
      periodCode:
        maxLength: 1
        minLength: 1
        type: string
      provider:
        $ref: '#/definitions/ProviderType'
      typeCode:
        maxLength: 1
        minLength: 1
        type: string
    required:
      - provider
      - issueDate
      - typeCode
    type: object
  ServiceMessageType:
    properties:
      code:
        type: string
      reason:
        type: string
      severity:
        enum:
          - Fatal
          - Error
          - Warning
          - Informational
        type: string
    required:
      - code
      - severity
      - reason
    type: object
  ServiceMessagesType:
    properties:
      highestSeverity:
        enum:
          - Fatal
          - Error
          - Warning
          - Informational
        type: string
      serviceMessage:
        items:
          $ref: '#/definitions/ServiceMessageType'
        minItems: 1
        type: array
    required:
      - highestSeverity
      - serviceMessage
    type: object
  ServiceType:
    discriminator: serviceType
    properties:
      accessionDateTime:
        format: date-time
        type: string
      aftercareOverrideInd:
        maxLength: 1
        minLength: 1
        type: string
      chargeAmount:
        maxLength: 9
        minLength: 1
        type: string
      collectionDateTime:
        format: date-time
        type: string
      duplicateServiceOverrideInd:
        maxLength: 1
        minLength: 1
        type: string
      fieldQuantity:
        maxLength: 2
        minLength: 1
        type: string
      id:
        maxLength: 4
        minLength: 4
        type: string
      itemNumber:
        maxLength: 5
        minLength: 1
        type: string
      lspNumber:
        maxLength: 6
        minLength: 1
        type: string
      multipleProcedureOverrideInd:
        maxLength: 1
        minLength: 1
        type: string
      numberOfPatientsSeen:
        maxLength: 2
        minLength: 1
        type: string
      restrictiveOverrideCode:
        maxLength: 2
        minLength: 2
        type: string
      rule3ExemptInd:
        maxLength: 1
        minLength: 1
        type: string
      s4b3ExemptInd:
        maxLength: 1
        minLength: 1
        type: string
      scpId:
        maxLength: 5
        minLength: 3
        type: string
      selfDeemedCode:
        maxLength: 2
        minLength: 1
        type: string
      text:
        type: string
      timeDuration:
        maxLength: 3
        minLength: 3
        type: string
    required:
      - id
    type: object
  StatusType:
    properties:
      code:
        type: integer
      text:
        type: string
    type: object
host: test.healthclaiming.api.humanservices.gov.au
info:
  contact:
    email: otsliaison@humanservices.gov.au
    name: DHS-Medicare
  description: Online Eligibility Check - Medicare only
  title: mcp.eligibility.check.medicare
  version: 1.0.0
  x-ibm-name: mcpeligibilitycheckmedicare
parameters:
  Authorization:
    default: Bearer REPLACE_THIS_KEY
    description: JWT header for authorization
    in: header
    name: Authorization
    required: true
    type: string
  dhs-auditId:
    default: LOC00001
    description: DHS Audit ID
    in: header
    name: dhs-auditId
    required: true
    type: string
  dhs-auditIdType:
    default: Location Id
    description: DHS Audit Type
    in: header
    name: dhs-auditIdType
    required: true
    type: string
  dhs-correlationId:
    default: urn:uuid:LOC00001a72594485d924214
    description: DHS Correlation ID
    in: header
    name: dhs-correlationId
    required: true
    type: string
  dhs-messageId:
    default: urn:uuid:a83f0c71-84a1-42c5-a442-51ea754f088e
    description: DHS Message ID
    in: header
    name: dhs-messageId
    required: true
    type: string
  dhs-productId:
    default: MyProduct 1.0
    description: DHS Product ID
    in: header
    name: dhs-productId
    required: true
    type: string
  dhs-subjectId:
    default: '2509999891'
    description: DHS Subject ID
    in: header
    name: dhs-subjectId
    required: true
    type: string
  dhs-subjectIdType:
    default: Medicare Card
    description: DHS Subject ID Type
    in: header
    name: dhs-subjectIdType
    required: true
    type: string
paths:
  /mcp/onlineeligibilitycheck/medicare/v1:
    parameters:
      - $ref: '#/parameters/Authorization'
      - $ref: '#/parameters/dhs-auditId'
      - $ref: '#/parameters/dhs-subjectId'
      - $ref: '#/parameters/dhs-messageId'
      - $ref: '#/parameters/dhs-auditIdType'
      - $ref: '#/parameters/dhs-correlationId'
      - $ref: '#/parameters/dhs-productId'
      - $ref: '#/parameters/dhs-subjectIdType'
    post:
      operationId: mcp-eligibility-check-medicare@1-eigw
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/OnlineEligibilityCheckRequestType'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/OnlineEligibilityCheckResponseType'
        '400':
          description: server cannot or will not process the request
          schema:
            $ref: '#/definitions/ServiceMessagesType'
      summary: This is the request
produces:
  - application/json
schemes:
  - https
security:
  - clientID: []
securityDefinitions:
  clientID:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
swagger: '2.0'
tags: []
x-ibm-configuration:
  cors:
    enabled: true
  enforced: true
  phase: realized
  testable: true
  type: rest
  servers:
    - url: https://test.healthclaiming.api.humanservices.gov.au/claiming/ext-vnd
      description: ''
      type:
        - production
        - development
    - url: https://test.healthclaiming.api.humanservices.gov.au/claiming/ext-vnd
      description: ''
      type:
        - production
        - development
